[player]
name = steve

[graphics]
fast_leaves = true
render_distance = 7

[game]
save_chunks = false
load_chunks = true

[worldgen]
superflat = true
generate_caves = true
generate_features = true
;set_seed = 1000

[controls]
sensitivity = 0.0075

[gui]
scale = 2
